### ISSUE TITLE
is there character length limit? : nchar(x) < 32700

### ISSUE THREAD

**Issue by Curycu** [ianmcook/implyr#45] opened 2020-07-20 02:56 UTC
I downloaded area json text from impala by implyr package & get broken json text when json text length is more than 32700.
Is there character length limit? 

p.s. 
data download result with python impyla is normal.

**Comment by ianmcook** [comment] 2020-07-21 21:49
Hi @Curycu, could you tell me which driver you are using to connect to Impala (ODBC or JDBC) and what the version of the driver is? Thanks!

**Comment by Curycu** [comment] 2020-07-22 01:47
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.5

Cloudera ODBC Driver for Impala (ClouderaImpalaODBC.dmg : $driver_version_sb$: 2.6.5.1005)

**Comment by ianmcook** [comment] 2020-07-23 19:56
Hi @Curycu, I was able to reproduce this issue in which `STRING` columns are truncated to 32767 characters. This is caused by the Cloudera ODBC Driver for Impala. Two possible solutions are:
 - Upgrade to a newer version of the ODBC driver. I believe (but I am not certain) that this limitation has been resolved in the latest version of the ODBC driver.
- Set the variable `StringColumnLength` in your ODBC configuration. For example, if you're using an  `odbcinst.ini` file, then add a line like this in it:

```
StringColumnLength=32767
```
Set the value to a larger number to enable longer `STRING` columns.

If neither of these solutions works for you, you might want to open a ticket with Cloudera and our support staff can investigate further.

**Comment by Curycu** [comment] 2020-07-24 08:26
upgrade to 2.6.10 odbc version & add `StringColumnLength` variable but still same problem occurs.. 
so I'll open a ticket. thank you for your kind help.

**Closed** 2020-07-24 08:36 UTC

**Comment by ianmcook** [comment] 2020-07-24 11:26
Thanks. If you email me at ian at cloudera dot com I'll make sure your support ticket gets attention.

**Comment by ianmcook** [comment] 2020-08-20 15:07
Hi @Curycu, the release notes for the new Impala ODBC driver version 2.6.11 indicates that this issue has been fixed:
> [IMP-789][00208980] The driver imposes a minimum (255) and maximum (32,767) character length for the StringColumnLength connection property.
> This issue has been resolved. The minimum limit has been set to 1 and values larger than 32,767 can now be set.

See https://docs.cloudera.com/documentation/other/connectors/impala-odbc/2-6-11.html.
