### ISSUE TITLE
dbDisconnect error on CentOS

### ISSUE THREAD

**Issue by mpgilliam** [ianmcook/implyr#22] opened 2018-03-01 21:40 UTC
When executing the code example of connecting to Impala, running a query, and disconnecting as shown in the README there is an error "type must be a single element of type 'character'" when attempting to disconnect. OS: CentOS, Implyr Version: 0.2.2

**Comment by ianmcook** [comment] 2018-03-02 00:44
I'm not able to reproduce this error in my tests on CentOS. Can you paste the code you're using to connect and disconnect? Thanks.

**Comment by mpgilliam** [comment] 2018-03-02 18:30
Code Ran:
library(odbc) # Version 1.1.5
library(dplyr) # Version 0.7.4
library(implyr) # Version 0.2.2
drv <- odbc::odbc()
imp <- src_impala(drv = drv, driver = "Cloudera ODBC Driver for Impala", host = "IP", port = 21050, database = "DB")
df <- dbGetQuery(imp, "select * from DB.TABLE")
dbDisconnect(imp)

Error Received:
Error: type must be a single element of type 'character'

System Info:
$ lsb_release -a
LSB Version: :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.9 (Final)
Release:        6.9
Codename:       Final

**Comment by ianmcook** [comment] 2018-03-02 20:54
This looks like a method dispatch error. implyr passes along the `dbDisconnect()` call to the underlying connection in `imp$con` but it looks like something might be going wrong there. Does the error go away if you do: `dbDisconnect(imp$con)`?

**Comment by mpgilliam** [comment] 2018-03-07 18:25
I am still recieveing the same error with the dbDisconnect(imp$con) line.
![image](https://user-images.githubusercontent.com/7211232/37110422-d8e6ce88-220a-11e8-9328-70c45ff7d2a1.png)

**Comment by ianmcook** [comment] 2018-03-09 02:14
This is mystifying me. Can you run `traceback()` immediately after the error occurs and paste the output here? That should help me to understand which function in which package is throwing the error. Thanks.

**Comment by ianmcook** [comment] 2018-03-13 17:12
I was finally able to reproduce this error. I'll work on resolving it as soon as I can.

**Comment by ianmcook** [comment] 2018-03-13 18:05
This is fixed in the version of implyr on GitHub (https://github.com/ianmcook/implyr/commit/67ba460ebcb307787c9d13e997fc2a97029a66e3).

Can you install the development version of implyr from GitHub to see if this solves the problem for you?
`devtools::install_github("ianmcook/implyr")`

I will include this fix in the next CRAN release of implyr.

**Comment by ianmcook** [comment] 2018-03-18 20:58
This is fixed in implyr version 0.2.3 on CRAN.

**Closed by ianmcook** 2018-03-18 20:58 UTC
